name: Pull Request

on:
  pull_request:
  push:
    tags:
      - "*"

jobs:
  style-prettier:
    name: style
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tek-engineering/tsp-toolkit-build:latest
      credentials:
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    steps:
      - name: Tool Versions
        run: npx prettier --version
      - name: Checkout
        uses: actions/checkout@v3
      - name: run prettier
        run: npx prettier --list-different
    

  compile:
    name: compile
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tek-engineering/tsp-toolkit-build:latest
      credentials:
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Tool Versions
        run: npm --version
      - name: install node
        uses: actions/setup-node@v3
       
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
          npm install
        
      - name: Build
        run: npm run compile
      - name: npm Package
        run: |
          npx vsce package --pre-release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: "*.vsix"
  
  package:
    name: Package
    runs-on: ubuntu-latest
    needs: compile
    container:
      image: ghcr.io/tek-engineering/tsp-toolkit-build:latest
      credentials:
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Tool Versions
        run: npm --version
      - name: Checkout
        uses: actions/checkout@v3
      - name: npm Package
        run: |
          npx vsce package --pre-release
          cp *.vsix tsp-toolkit.vsix
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: "*.vsix"