name: Pull Request

on:
  pull_request:
  push:
    tags:
      - "*"

jobs:
  style-prettier:
    name: style
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tek-engineering/tsp-toolkit-build:latest
      credentials:
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    steps:
      - name: Tool Versions
        run: npx prettier --version
      - name: Checkout
        uses: actions/checkout@v3
      - name: run prettier
        run: npx prettier --list-different
    

  compile:
    name: compile
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tek-engineering/tsp-toolkit-build:latest
      credentials:
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Tool Versions
        run: npm --version
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@tek-engineering'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
          npm install
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Build
        run: npm run compile
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: out
          path: |
            out/
  
  package:
    name: Package
    runs-on: ubuntu-latest
    needs: compile
    container:
      image: ghcr.io/tek-engineering/tsp-toolkit-build:latest
      credentials:
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Tool Versions
        run: npm --version
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Artifacts
        uses: actions/download-artifact@v3
        with:
          name: executable
          path: target/
      - name: npm Package
        run: |
          npx vsce package --pre-release --baseContentUrl https://git.keithley.com/trebuchet/teaspoon/teaspoon/
          cp *.vsix tsp-toolkit.vsix
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: "*.vsix"