name: Pull Request

on:
  pull_request:
  push:
    tags:
      - "*"

jobs:
  style:
    name: style
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tek-engineering/tsp-toolkit-build:latest
      credentials:
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    steps:
      - name: Tool Versions
        run: npx prettier --version
      - name: Checkout
        uses: actions/checkout@v3
      - name: run prettier
        run: npx prettier --list-different
    
  lint:
    name: lint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tek-engineering/tsp-toolkit-build:latest
      credentials:
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    steps:
      - name: Tool Versions
        run: npx eslint --version
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
          npm install
      - name: Run eslint
        run: 'npx eslint --rule "{ prettier/prettier: off }" src'
  
  test:
    name: test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tek-engineering/tsp-toolkit-build:latest
      credentials:
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    steps:
      - name: Tool Versions
        run: npx prettier --version
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
          npm install
      - name: Run Tests with Coverage
        run: npx nyc --nycrc-path=.nycrc.json npm run test-ci
      - name: Generate Coverage Reports
        run: npx nyc report --reporter=cobertura --reporter=text

  compile:
    name: compile
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tek-engineering/tsp-toolkit-build:latest
      credentials:
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Tool Versions
        run: npm --version  
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
          npm install
        
      - name: Build
        run: npm run compile
      - name: npm Package
        run: |
          npx vsce package --pre-release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: "*.vsix"
  
  # package:
  #   name: Package
  #   runs-on: ubuntu-latest
  #   needs: compile
  #   container:
  #     image: ghcr.io/tek-engineering/tsp-toolkit-build:latest
  #     credentials:
  #       username: ${{github.actor}}
  #       password: ${{secrets.GITHUB_TOKEN}}
  #   steps:
  #     - name: Tool Versions
  #       run: npm --version
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: npm Package
  #       run: |
  #         npx vsce package --pre-release
  #         cp *.vsix tsp-toolkit.vsix
  #     - name: Upload Artifacts
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: package
  #         path: "*.vsix"